name: Build and deploy Python app to Azure Web App

env:
  AZURE_WEBAPP_NAME: SKPH-IO-FTIMS
  PYTHON_VERSION: '3.12'

# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:

jobs:
  build:
    name: Build app and upload artifact
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate translations
        run: |
          pybabel extract -F babel.cfg -o messages.pot .
          pybabel update -i messages.pot -d translations
          pybabel compile -d translations

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !venv/

  deploy:
    name: Deploy to Azure Web App
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 10

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: .

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@85270a1854658d167ab239bce43949edb336fa7c
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
